### ISSUE TITLE
Customize keybind-label-returncode pairs

### ISSUE THREAD

**Issue by mriehl** [brocode/goat#1]
`goat --mapping "q:1:Abort" --mapping "d:2:Abort and delete"` or something.

I'd like to specify (multiple times)
- what key to press
- a label
- what the returncode will be

cc @bomgar

**Comment by mriehl** [comment]
By default `goat` should only handle "the user did not press anything" and exit with 0.

Actually I am not sure yet if the return code is really a good idea to signal what happened because >0 suggests failure. So it's really weird in-band signalling (especially with the `-e` bash option)

**Comment by bomgar** [comment]
maybe we should define a range for errors. like real error returncode > 100

**Comment by mriehl** [comment]
According to http://tldp.org/LDP/abs/html/exitcodes.html I'll allow 64-113
